---
- name: Deploy - PwC Alumni - Dev Environment
  gather_facts: No
  hosts: vm-pwcdev

  tasks:
    - import_tasks: tasks/packages.yaml 
    - name: Enable and Running Httpd
      systemd:
        name: httpd
        enabled: yes
        state: started
    - name: Enable Firewall Rules (http)
      firewalld:
        service: http
        permanent: yes
        zone: public
        state: enabled
        immediate: yes
    - name: Enable Firewall Rules (https)
      firewalld:
        service: https
        zone: public
        permanent: yes
        state: enabled
        immediate: yes
    - name: Install PHP Composer (1/3)
      get_url:
        url: https://getcomposer.org/download/1.9.3/composer.phar  
        dest: /usr/local/bin
    - name: Install PHP Composer (2/3)
      command: mv /usr/local/bin/composer.phar /usr/local/bin/composer
    - name: Install PHP Composer (3/3)
      command: chmod +x /usr/local/bin/composer
    - name: Prepare Laravel Setup (1/2)
      file:
        path: /srv/www/app/http
        state: directory
    - name: Prepare Laravel Setup (2/2)
      file:
        path: /srv/www/app/logs
        state: directory
    - name: Check laravel App Exists 
      stat: 
        path: /srv/www/app/http/.env
      register: laravel_check
    - debug:
        msg: "Laravel not installed"
      when: laravel_check.stat.exists == False
    - name: Install Laravel Framework
      command: composer create-project --prefer-dist laravel/laravel /srv/www/app/http/
      when: laravel_check.stat.exists == False
