---
- name: Deploy - PwC Alumni - Dev Environment
  gather_facts: No
  hosts: vm-pwcdev

  tasks:
    - name: Install CentOS Update 
      yum:
        name: '*'
        state: latest
    - name: Install Httpd 
      yum:
        name: httpd
        state: latest
    - name: Install Epel-Release
      yum:
        name: epel-release
        state: latest
    - name: Install yum-utils
      yum:
        name: yum-utils
        state: latest
    - name: Install Remi Repository (PHP)
      yum:
        name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
        state: latest
        enablerepo: "remi-php72"
    - name: Install PHP (7.2) Modules
      yum:
        name: 
          - php 
          - php-common 
          - php-opcache 
          - php-mcrypt 
          - php-cli 
          - php-gd 
          - php-curl 
          - php-mysqlnd
          - php-pdo
          - php-mbstring
          - php-json
          - php-xml
    - name: Install Git
      yum:
        name: git
        state: latest 
    - name: Enable and Running Httpd
      systemd:
        name: httpd
        enabled: yes
        state: started
    - name: Enable Firewall Rules (http)
      firewalld:
        service: http
        permanent: yes
        zone: public
        state: enabled
        immediate: yes
    - name: Enable Firewall Rules (https)
      firewalld:
        service: https
        zone: public
        permanent: yes
        state: enabled
        immediate: yes
    - name: Install PHP Composer (1/3)
      get_url:
        url: https://getcomposer.org/download/1.9.3/composer.phar  
        dest: /usr/local/bin
    - name: Install PHP Composer (2/3)
      command: mv /usr/local/bin/composer.phar /usr/local/bin/composer
    - name: Install PHP Composer (3/3)
      command: chmod +x /usr/local/bin/composer
        
